### ISSUE TITLE
Use @DynamicPropertySource instead of ApplicationContextInitializer in Junits

### ISSUE THREAD

**Issue by rajadilipkolli** [sivaprasadreddy/generator-springboot#23]
Use @DynamicPropertySource like [here](https://github.com/rajadilipkolli/analytics-spring-cloud-streams-kafka/blob/master/analytics-spring-cloud-streams-kafka-consumer/src/test/java/com/example/analytics/AnalyticsConsumerApplicationTests.java#L51-L58) instead of [ApplicationContextInitializer](https://github.com/sivaprasadreddy/generator-springboot/blob/master/generators/server/templates/app/src/test/java/common/DBContainerInitializer.java#L19) in Junits when using Containers for setting the value in Junit tests  [example](https://www.baeldung.com/spring-dynamicpropertysource)

Also use @TestContainers annotation in conjunction with @Container annotation to start the container.

If we need to use the database across all Junits then we need to create ShareContainer like [here](https://github.com/rajadilipkolli/spring-boot-microservices-series-gradle/tree/master/catalog-service/src/test/java/com/example/catalogservice/common)

Suggest which is better way to handle?

I will submit PR for this

**Comment by sivaprasadreddy** [comment]
I remember changing it to use @DynamicPropertySource and reverting it back to ApplicationContextInitializer for some reason. Couldn't recollect the reason off top of my head.

Basically, I am aiming for having separate classes for Database/Localstack etc containers so that I can use them separately for specific scenarios, or use them all combined to run integration tests.

For example, if I want to run Spring Data JPA repository tests with @DataJpaTest I would like to use DBContainerInitializer. If I want to run some integration test with @SpringBootTest then I would like to use same DBContainerInitializer and LocalStackContainerInitializer without having to configure DB container for integration tests again separately.

If that can be done with @DynamicPropertiesSource then we can update it.

**Comment by rajadilipkolli** [comment]
I will check sharing of containers for multiple tests from different classes

**Comment by rajadilipkolli** [comment]
Please go through this link https://rieckpil.de/reuse-containers-with-testcontainers-for-fast-integration-tests/ it helps to use @DynamicProperties

**Comment by sivaprasadreddy** [comment]
In order to use @DynamicPropertiesSource we need to have a base class with ALL the containers defined. It would become bulky as and when we add more containers. Also, ApplicationContextInitializers play nice when running tests parallelly as opposed to having a base class with static containers.

So, for now, let us continue with current approach.
