### ISSUE TITLE
Code Clean up for 0.1.3 version

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/generator-springboot#80]
Considering the new features introduced in Spring Boot 3.1.0, I have the following things that can clean up our code generation process:

1. Do we need Spring Cloud BOM Configuration?
2. Remove milestone and snapshot reposiotry configurations
3. Do we need .editorconfig?
4. Rename `ErrorDetailProblemHandlingControllerAdvice` to `GlobalExceptionHandler` and move into `com.mycompany.<service>.config` package.
5. Shall we remove `application-heroku.properties`, `application-local.properties`?
6. Shall we remove generating h2 db migration scripts by default and provide H2 as one of the database option?
7. When using MySQL database tests are failing with SSL errors.

**Comment by rajadilipkolli** [comment]
> Considering the new features introduced in Spring Boot 3.1.0, I have the following things that can clean up our code generation process:
> 
> 1. Do we need Spring Cloud BOM Configuration?
> 2. Remove milestone and snapshot reposiotry configurations
> 3. Do we need .editorconfig?
> 4. Rename `ErrorDetailProblemHandlingControllerAdvice` to `GlobalExceptionHandler` and move into `com.mycompany.<service>.config` package.
> 5. Shall we remove `application-heroku.properties`, `application-local.properties`?
> 6. Shall we remove generating h2 db migration scripts by default and provide H2 as one of the database option?
> 7. When using MySQL database tests are failing with SSL errors.

Hi @sivaprasadreddy, below are my comments. we can discuss and come up with a conclusion

1.  BOM is necessary as we still provide option to end user to just add cloud dependency starter
2 and 3. Should be removed
4. Should be handled
5. we should remove `application-heroku.properties` and keep `application-local.properties` to support aws
6.  I feel we should keep it because it provides users to run application locally without docker.
7. Happening from spring boot, need to check workaround

**Comment by rajadilipkolli** [comment]
Task 2,3,5 completed in #81
